server:
  port: 19001
spring:
  application:
    name: ${project.artifactId}
logging:
  level:
    root: info
    io.github.atengk: debug
---
# Spring AI 配置
spring:
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    vectorstore:
      milvus:
        initialize-schema: true
        database-name: default
        collection-name: spring_ai_knowledge_ateng
        embedding-dimension: 1536
        metric-type: COSINE
        index-type: IVF_FLAT
        index-parameters: '{"nlist":1024}'

        id-field-name: id
        content-field-name: content
        metadata-field-name: metadata
        embedding-field-name: embedding

        auto-id: false

        client:
          host: 175.178.193.128
          port: 20016
          username: root
          password: Milvus
          secure: false

    openai:
      base-url: https://api.chatanywhere.tech
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
    mcp:
      client:
        sse:
          connections:
            local-mcp:
              url: http://localhost:19002
              sse-endpoint: /sse
        name: ateng-mcp-client
        version: 1.0.0
---
spring:
  datasource:
    url: jdbc:mysql://175.178.193.128:20001/kongyu
    username: kongyu
    password: kongyu
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 30000
