server:
  port: 19001
spring:
  application:
    name: ${project.artifactId}
---
# Spring AI 配置
spring:
  ai:
    deepseek:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-v3.2
          temperature: 0.7
