server:
  port: 18002
spring:
  application:
    name: ${project.artifactId}
logging:
  level:
    root: info
    io.github.atengk: debug
---
# Redis的相关配置
spring:
  data:
    redis:
      host: 175.178.193.128 # Redis服务器地址
      database: 1 # Redis数据库索引（默认为0）
      port: 20003 # Redis服务器连接端口
      password: Admin@123 # Redis服务器连接密码（默认为空）
      client-type: lettuce  # 默认使用Lettuce作为Redis客户端
      lettuce:
        pool:
          max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1s # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 100 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池最小空闲连接数
          time-between-eviction-runs: 1s # 空闲对象逐出器线程的运行间隔时间.空闲连接线程释放周期时间
      timeout: 5000ms # 连接超时时间（毫秒）
---
# WebSocket + STOMP Broker Relay 配置
websocket:
  url: /ws                     # WebSocket 端点
  allowed-origins: "*"          # 跨域允许
  heartbeat-interval: 30000     # 前端心跳发送间隔 ms
  application-destination-prefix: /app
  user-destination-prefix: /user
  heartbeat-destination: /app/heartbeat # 心跳发送地址
  broker-relay:
    relay-host: 175.178.193.128
    relay-port: 20015
    client-login: admin
    client-passcode: Admin@123
    system-login: admin
    system-passcode: Admin@123
    system-heartbeat-send-interval: 10000
    system-heartbeat-receive-interval: 10000


